file(GLOB public_headers
  "${SHELLCLAVE_SOURCE_DIR}/shellsplit/include/*.h"
  "${SHELLCLAVE_SOURCE_DIR}/shelltype/include/*.h"
  "${SHELLCLAVE_SOURCE_DIR}/shellgate/include/*.h")

set(removed_identifiers
  st_policy_ctx_free
  st_policy_ctx_compact
  st_policy_ctx_intern
  st_policy_ctx_is_exclusive
  st_node_t
  st_trie_t
  st_policy_count
  st_policy_free_matches
  st_feed
  st_feed_parsed
  st_suggest
  st_free_suggestions
  st_free_token_array
  st_free_diff_result
  st_blacklist_add_netpattern
  st_is_netpattern_blacklisted
  st_save
  st_load
  st_classify
  st_classify_token
  st_validate_netpattern
  sg_eval
  sg_eval_size_hint
  sg_gate_set_violation_config
  sg_subcmd_result_t
  sg_gate_set_anomaly_update_on_non_anomaly
  sg_gate_add_rule
  sg_gate_remove_rule
  sg_gate_add_deny_rule
  sg_gate_remove_deny_rule
  sg_gate_rule_count
  sg_gate_add_allow_cpl_rule
  sg_gate_remove_allow_cpl_rule
  sg_gate_add_deny_cpl_rule
  sg_gate_remove_deny_cpl_rule
  sg_gate_suggestion_token_variants_at
  sg_anomaly_model_new_ex
  sg_anomaly_model_total_uni
  sg_anomaly_model_total_bi
  sg_anomaly_model_total_tri
  sg_anomaly_model_total_quad
  sg_anomaly_model_uni_count
  sg_anomaly_model_unk_count
  sg_anomaly_model_kn_discount
  sg_anomaly_model_bi_count
  sg_anomaly_model_tri_count
  sg_anomaly_model_quad_count
  sg_anomaly_score_netseq
  sg_anomaly_update_netseq
  sg_anomaly_save
  sg_anomaly_load
  sg_anomaly_vocab_size
  sg_anomaly_total_uni
  sg_anomaly_total_bi
  sg_anomaly_total_tri
  sg_anomaly_total_quad
  sg_anomaly_uni_count
  sg_anomaly_unk_count
  sg_anomaly_kn_discount
  sg_anomaly_bi_count
  sg_anomaly_tri_count
  sg_anomaly_quad_count
  sg_anomaly_total_contexts
  sg_anomaly_has_observed_netseq
  sg_anomaly_reset
  token_type_t
  abstract_type_t
  path_category_t
  abstract_element_t
  abstracted_command_t
  runtime_context_t
  transform_type_t
  transformed_token_t
  transformed_command_t
  ngram_entropy
  permutation_entropy
  relative_entropy_ratio
  conditional_entropy
  permutation_conditional_entropy
  relative_conditional_entropy
  env_screener_status_t
  env_screener_scan
  env_screener_calculate_entropy
  env_screener_is_secret_pattern
  env_screener_is_whitelisted
  env_screener_recommended_capacity
  env_screener_get_whitelist_doc
  env_screener_combined_score
  env_screener_combined_name
  looks_like_path
  looks_like_base64
  check_secret_prefix
  shell_abstracted_destroy
  shell_abstracted_command_t
  shell_abstracted_command_free
  shell_abstract_command
  shell_get_abstracted
  shell_get_original
  shell_get_elements
  shell_get_element_by_abstract
  shell_get_element_at
  shell_expand_element
  shell_expand_all_elements
  shell_get_path_category
  shell_get_subcommand
  shell_copy_subcommand
  shell_command_has_features
  shell_interop_create
  shell_interop_destroy
  shell_interop_subcommand_str
  shell_interop_free_str
  shell_interop_features_str
  shell_interop_type_str
  shell_free_command_infos
  shell_has_dangerous_features
  shell_free_commands
  shell_has_features
  shell_get_feature_flags
  shell_free_transformed_command
  shell_free_transformed_commands
  shell_get_dfa_input
  shell_has_transformations
  shell_parse_depgraph
  shell_transformed_command_get_dfa_input
  shell_transformed_commands_free
  shell_extract_netargv_sequence
  shell_interop_subcommand_type
  shell_interop_subcommand_features
  shell_interop_subcommand_start
  shell_interop_subcommand_len
  shell_interop_string_free
  shell_interop_feature_flags_to_string
  shell_interop_subcommand_type_to_string
  shell_abstract_command_get_text
  shell_transformed_command_get_text
  shell_dep_validate_result_t
  shell_dep_validate
  SG_MAX_SUBCMD_RESULTS
  subcmd_count
  subcmd_truncated
  cmd_node_index)

foreach(header IN LISTS public_headers)
  file(READ "${header}" contents)
  foreach(identifier IN LISTS removed_identifiers)
    if(contents MATCHES "(^|[^A-Za-z0-9_])${identifier}([^A-Za-z0-9_]|$)")
      message(FATAL_ERROR "removed public API identifier ${identifier} in ${header}")
    endif()
  endforeach()
  if(contents MATCHES "(^|[^A-Za-z0-9_])TOKEN_")
    message(FATAL_ERROR "unprefixed token enum in ${header}")
  endif()
  if(contents MATCHES "(^|[^A-Za-z0-9_])(ABSTRACT_|TRANSFORM_|PATH_(ROOT|ETC|VAR|USR|HOME|TMP|PROC|SYS|DEV|OPT|SRV|RUN|SYSROOT|BOOT|MNT|MEDIA|SNAPSHOT|OTHER))")
    message(FATAL_ERROR "unprefixed Shellsplit enum in ${header}")
  endif()
endforeach()
