#define _GNU_SOURCE
#define _POSIX_C_SOURCE 200809L

/*
 * normalize.c - Command normalisation with typed wildcard lattice.
 *
 * Classifies each token into the most specific type in the lattice.
 * Provides join and compatibility tables for policy generation and verification.
 *
 * NOTE: st_type_join and st_type_compatible are generated by tools/gen_lattice_tables.py
 * from a declarative lattice definition in that script. Do not edit these tables by hand;
 * instead update the lattice definition and regenerate.
 */

#include "shelltype.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <stdbool.h>

/* ============================================================
 * TYPE SYMBOLS
 * ============================================================ */

const char *st_type_symbol[ST_TYPE_COUNT] = {
    [ST_TYPE_LITERAL]       = "",
    [ST_TYPE_HEXHASH]       = "#h",
    [ST_TYPE_NUMBER]        = "#n",
    [ST_TYPE_IPV4]          = "#i",
    [ST_TYPE_WORD]          = "#w",
    [ST_TYPE_QUOTED]        = "#q",
    [ST_TYPE_QUOTED_SPACE]  = "#qs",
    [ST_TYPE_FILENAME]      = "#f",
    [ST_TYPE_REL_PATH]      = "#r",
    [ST_TYPE_ABS_PATH]      = "#p",
    [ST_TYPE_PATH]          = "#path",
    [ST_TYPE_URL]           = "#u",
    [ST_TYPE_VALUE]         = "#val",
    [ST_TYPE_OPT]           = "#opt",
    [ST_TYPE_UUID]          = "#uuid",
    [ST_TYPE_EMAIL]         = "#email",
    [ST_TYPE_HOSTNAME]      = "#host",
    [ST_TYPE_PORT]          = "#port",
    [ST_TYPE_SIZE]          = "#size",
    [ST_TYPE_SEMVER]        = "#semver",
    [ST_TYPE_TIMESTAMP]     = "#ts",
    [ST_TYPE_HASH_ALGO]     = "#hash",
    [ST_TYPE_ENV_VAR]       = "#env",
    [ST_TYPE_HYPHENATED]    = "#hyp",
    [ST_TYPE_ANY]           = "*",
};

/* ============================================================
 * JOIN TABLE
 *
 * st_type_join[a][b] = narrowest type covering both a and b.
 *
 * Lattice:
 *   #h ⊂ #n ⊂ #val ⊂ *
 *   #i ⊂ #val ⊂ *
 *   #w ⊂ #val ⊂ *
 *   #q ⊂ #qs ⊂ #val ⊂ *
 *   #f ⊂ #r ⊂ #path ⊂ *
 *   #p ⊂ #path ⊂ *
 *   #u ⊂ *
 *   #opt ⊂ #val ⊂ *
 *   #uuid, #email, #host, #size, #semver, #ts, #env ⊂ #val ⊂ *
 *   #port ⊂ #n, #port ⊂ #i, #port ⊂ #val ⊂ *
 *   #hash, #hyp ⊂ #w ⊂ #val ⊂ *
 * ============================================================ */

const st_token_type_t st_type_join[ST_TYPE_COUNT][ST_TYPE_COUNT] = {
    /*                LIT   HEX   NUM   IPV4  WORD  QOT   QS    FILE  REL   ABS   PATH  URL   VAL   OPT   UUID  EMAIL  HOST  PORT  SIZE  SEMV  TS    HASH  ENV   HYP   ANY  */
    /* ST_TYPE_LITERAL */
    { ST_TYPE_LITERAL, ST_TYPE_HEXHASH, ST_TYPE_NUMBER, ST_TYPE_IPV4, ST_TYPE_WORD, ST_TYPE_QUOTED, ST_TYPE_QUOTED_SPACE, ST_TYPE_FILENAME, ST_TYPE_REL_PATH, ST_TYPE_ABS_PATH, ST_TYPE_PATH, ST_TYPE_URL, ST_TYPE_VALUE, ST_TYPE_OPT, ST_TYPE_UUID, ST_TYPE_EMAIL, ST_TYPE_HOSTNAME, ST_TYPE_PORT, ST_TYPE_SIZE, ST_TYPE_SEMVER, ST_TYPE_TIMESTAMP, ST_TYPE_HASH_ALGO, ST_TYPE_ENV_VAR, ST_TYPE_HYPHENATED, ST_TYPE_ANY },
    /* ST_TYPE_HEXHASH */
    { ST_TYPE_HEXHASH, ST_TYPE_HEXHASH, ST_TYPE_NUMBER, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_NUMBER, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_NUMBER */
    { ST_TYPE_NUMBER, ST_TYPE_NUMBER, ST_TYPE_NUMBER, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_NUMBER, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_IPV4 */
    { ST_TYPE_IPV4, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_IPV4, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_IPV4, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_WORD */
    { ST_TYPE_WORD, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_WORD, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_WORD, ST_TYPE_VALUE, ST_TYPE_WORD, ST_TYPE_ANY },
    /* ST_TYPE_QUOTED */
    { ST_TYPE_QUOTED, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_QUOTED, ST_TYPE_QUOTED_SPACE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_QUOTED_SPACE */
    { ST_TYPE_QUOTED_SPACE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_QUOTED_SPACE, ST_TYPE_QUOTED_SPACE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_FILENAME */
    { ST_TYPE_FILENAME, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_FILENAME, ST_TYPE_REL_PATH, ST_TYPE_PATH, ST_TYPE_PATH, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY },
    /* ST_TYPE_REL_PATH */
    { ST_TYPE_REL_PATH, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_REL_PATH, ST_TYPE_REL_PATH, ST_TYPE_PATH, ST_TYPE_PATH, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY },
    /* ST_TYPE_ABS_PATH */
    { ST_TYPE_ABS_PATH, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_PATH, ST_TYPE_PATH, ST_TYPE_ABS_PATH, ST_TYPE_PATH, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY },
    /* ST_TYPE_PATH */
    { ST_TYPE_PATH, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_PATH, ST_TYPE_PATH, ST_TYPE_PATH, ST_TYPE_PATH, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY },
    /* ST_TYPE_URL */
    { ST_TYPE_URL, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_URL, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY },
    /* ST_TYPE_VALUE */
    { ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_OPT */
    { ST_TYPE_OPT, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_OPT, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_UUID */
    { ST_TYPE_UUID, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_UUID, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_EMAIL */
    { ST_TYPE_EMAIL, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_EMAIL, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_HOSTNAME */
    { ST_TYPE_HOSTNAME, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_HOSTNAME, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_PORT */
    { ST_TYPE_PORT, ST_TYPE_NUMBER, ST_TYPE_NUMBER, ST_TYPE_IPV4, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_PORT, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_SIZE */
    { ST_TYPE_SIZE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_SIZE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_SEMVER */
    { ST_TYPE_SEMVER, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_SEMVER, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_TIMESTAMP */
    { ST_TYPE_TIMESTAMP, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_TIMESTAMP, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_HASH_ALGO */
    { ST_TYPE_HASH_ALGO, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_WORD, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_HASH_ALGO, ST_TYPE_VALUE, ST_TYPE_WORD, ST_TYPE_ANY },
    /* ST_TYPE_ENV_VAR */
    { ST_TYPE_ENV_VAR, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ENV_VAR, ST_TYPE_VALUE, ST_TYPE_ANY },
    /* ST_TYPE_HYPHENATED */
    { ST_TYPE_HYPHENATED, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_WORD, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_VALUE, ST_TYPE_WORD, ST_TYPE_VALUE, ST_TYPE_HYPHENATED, ST_TYPE_ANY },
    /* ST_TYPE_ANY */
    { ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY, ST_TYPE_ANY },
};

/* ============================================================
 * COMPATIBILITY TABLE
 *
 * st_type_compatible[cmd_type][policy_type] = true iff cmd_type ≤ policy_type.
 * A command token of cmd_type matches a policy node of policy_type.
 *
 * Derived from the same lattice via transitive closure.
 * ============================================================ */

const bool st_type_compatible[ST_TYPE_COUNT][ST_TYPE_COUNT] = {
    /* ST_TYPE_LITERAL matches: LITERAL, HEXHASH, NUMBER, IPV4, WORD, QUOTED, QUOTED_SPACE, FILENAME, REL_PATH, ABS_PATH, PATH, URL, VALUE, OPT, UUID, EMAIL, HOSTNAME, PORT, SIZE, SEMVER, TIMESTAMP, HASH_ALGO, ENV_VAR, HYPHENATED, ANY */
    { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true },
    /* ST_TYPE_HEXHASH matches: HEXHASH, NUMBER, VALUE, ANY */
    { false, true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_NUMBER matches: NUMBER, VALUE, ANY */
    { false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_IPV4 matches: IPV4, VALUE, ANY */
    { false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_WORD matches: WORD, VALUE, ANY */
    { false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_QUOTED matches: QUOTED, QUOTED_SPACE, VALUE, ANY */
    { false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_QUOTED_SPACE matches: QUOTED_SPACE, VALUE, ANY */
    { false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_FILENAME matches: FILENAME, REL_PATH, PATH, ANY */
    { false, false, false, false, false, false, false, true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_REL_PATH matches: REL_PATH, PATH, ANY */
    { false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_ABS_PATH matches: ABS_PATH, PATH, ANY */
    { false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_PATH matches: PATH, ANY */
    { false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_URL matches: URL, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_VALUE matches: VALUE, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_OPT matches: VALUE, OPT, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_UUID matches: VALUE, UUID, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_EMAIL matches: VALUE, EMAIL, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true },
    /* ST_TYPE_HOSTNAME matches: VALUE, HOSTNAME, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true },
    /* ST_TYPE_PORT matches: NUMBER, IPV4, VALUE, PORT, ANY */
    { false, false, true, true, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true },
    /* ST_TYPE_SIZE matches: VALUE, SIZE, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true },
    /* ST_TYPE_SEMVER matches: VALUE, SEMVER, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, true },
    /* ST_TYPE_TIMESTAMP matches: VALUE, TIMESTAMP, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true },
    /* ST_TYPE_HASH_ALGO matches: WORD, VALUE, HASH_ALGO, ANY */
    { false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, true },
    /* ST_TYPE_ENV_VAR matches: VALUE, ENV_VAR, ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, true },
    /* ST_TYPE_HYPHENATED matches: WORD, VALUE, HYPHENATED, ANY */
    { false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, true },
    /* ST_TYPE_ANY matches: ANY */
    { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true },
};


/* ============================================================
 * CLASSIFICATION HELPERS
 * ============================================================ */

static bool is_decimal_number(const char *token)
{
    if (!token[0]) return false;
    const char *p = token;
    if (*p == '-') p++;
    if (!*p) return false;
    while (*p) {
        if (!isdigit((unsigned char)*p)) return false;
        p++;
    }
    return true;
}

static bool is_hex_number(const char *token)
{
    if (token[0] == '0' && (token[1] == 'x' || token[1] == 'X')) {
        if (!token[2]) return false;
        for (const char *p = token + 2; *p; p++) {
            if (!isxdigit((unsigned char)*p)) return false;
        }
        return true;
    }
    return false;
}

static bool is_hex_hash(const char *token)
{
    size_t len = strlen(token);
    if (len < 8) return false;
    bool has_alpha = false;
    for (size_t i = 0; i < len; i++) {
        unsigned char c = (unsigned char)token[i];
        if (!isxdigit(c)) return false;
        if (isalpha(c)) has_alpha = true;
    }
    return has_alpha;
}

static bool is_ipv4(const char *token)
{
    int dots = 0;
    const char *p = token;
    while (*p) {
        if (*p == '.') dots++;
        else if (!isdigit((unsigned char)*p)) return false;
        p++;
    }
    return dots == 3;
}

static bool is_absolute_path(const char *token)
{
    return token[0] == '/' && token[1] != '\0';
}

static bool is_relative_path(const char *token)
{
    /* Contains ".." or "/" but does not start with "/" */
    if (token[0] == '/') return false;
    if (strstr(token, "..") != NULL) return true;
    if (strchr(token, '/') != NULL) return true;
    return false;
}

static bool is_filename(const char *token)
{
    /* No "/", has "." (extension), not a number/word/etc. */
    if (strchr(token, '/') != NULL) return false;
    if (strchr(token, '.') == NULL) return false;
    return true;
}

static bool is_url(const char *token)
{
    /* protocol://... */
    const char *colon = strchr(token, ':');
    if (!colon) return false;
    if (colon[1] != '/' || colon[2] != '/') return false;
    /* Check protocol part is alphabetic */
    for (const char *p = token; p < colon; p++) {
        if (!isalpha((unsigned char)*p)) return false;
    }
    return true;
}

static bool has_whitespace(const char *token)
{
    for (const char *p = token; *p; p++) {
        if (isspace((unsigned char)*p)) return true;
    }
    return false;
}

static bool is_option_token(const char *token)
{
    /* Short option: -x (single letter after dash, not digit)
     * Long option: --word (double dash, then letters/digits/hyphens) */
    if (token[0] != '-') return false;
    if (token[1] == '-') {
        /* Long option: --word or --word=value */
        if (!token[2]) return false;  /* Just "--" is not an option */
        for (const char *p = token + 2; *p; p++) {
            if (isalnum((unsigned char)*p) || *p == '-' || *p == '=') continue;
            return false;
        }
        return true;
    } else if (token[1] && !isspace((unsigned char)token[1])) {
        /* Short option: -x (single letter after dash)
         * Must be alpha, not digit (digits are caught by number classification) */
        return isalpha((unsigned char)token[1]);
    }
    return false;
}

static bool is_uuid(const char *token)
{
    /* UUID format: 8-4-4-4-12 hex digits (e.g., 550e8400-e29b-41d4-a716-446655440000) */
    size_t len = strlen(token);
    if (len != 36) return false;

    static const int segments[] = {8, 4, 4, 4, 12};
    int pos = 0;

    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < segments[i]; j++) {
            char c = token[pos++];
            if (!isxdigit((unsigned char)c)) return false;
        }
        if (i < 4) {
            if (token[pos++] != '-') return false;
        }
    }
    return token[pos] == '\0';
}

static bool is_email(const char *token)
{
    /* Email format: user@domain */
    const char *at = strchr(token, '@');
    if (!at) return false;
    if (at == token) return false;
    if (at[1] == '\0') return false;

    /* Check user part */
    for (const char *p = token; p < at; p++) {
        char c = *p;
        if (isalnum((unsigned char)c) || c == '.' || c == '_' || c == '-' || c == '+') continue;
        return false;
    }

    /* Check domain part */
    const char *domain = at + 1;
    if (strchr(domain, '.') == NULL) return false;
    for (const char *p = domain; *p; p++) {
        char c = *p;
        if (isalnum((unsigned char)c) || c == '.' || c == '-') continue;
        return false;
    }
    return true;
}

static bool is_hostname(const char *token)
{
    /* Hostname/domain: alphanumeric with hyphens and dots, starts and ends with alphanumeric, contains hyphen */
    size_t len = strlen(token);
    if (len == 0) return false;
    if (token[0] == '-' || token[len-1] == '-') return false;
    if (!isalnum((unsigned char)token[0]) || !isalnum((unsigned char)token[len-1])) return false;

    bool has_hyphen = false;
    bool has_dot = false;
    for (size_t i = 0; i < len; i++) {
        char c = token[i];
        if (c == '-') {
            has_hyphen = true;
            if (i > 0 && token[i-1] == '-') return false;
        } else if (c == '.') {
            has_dot = true;
            if (i > 0 && token[i-1] == '.') return false;
        } else if (!isalnum((unsigned char)c)) {
            return false;
        }
    }
    return has_hyphen && has_dot;
}

static bool is_port(const char *token)
{
    /* Port: positive integer in range 1-65535 */
    if (!is_decimal_number(token)) return false;
    if (token[0] == '-') return false;

    long port = 0;
    for (const char *p = token; *p; p++) {
        port = port * 10 + (*p - '0');
        if (port > 65535) return false;
    }
    return port >= 1 && port <= 65535;
}

static bool is_size(const char *token)
{
    /* Size: number followed by suffix (K, M, G, T, Ki, Mi, Gi, Ti, KB, MB, GB, TB, bytes, b) */
    size_t len = strlen(token);
    if (len < 2) return false;

    size_t num_end = 0;
    while (num_end < len && (isdigit((unsigned char)token[num_end]) || token[num_end] == '.')) {
        num_end++;
    }
    if (num_end == 0) return false;

    bool has_digit = false;
    for (size_t i = 0; i < num_end; i++) {
        if (isdigit((unsigned char)token[i])) {
            has_digit = true;
            break;
        }
    }
    if (!has_digit) return false;

    if (num_end == len) return false;

    const char *suffix = token + num_end;

    if (strcmp(suffix, "Ki") == 0 || strcmp(suffix, "Mi") == 0 ||
        strcmp(suffix, "Gi") == 0 || strcmp(suffix, "Ti") == 0) {
        return true;
    }

    if (strcmp(suffix, "K") == 0 || strcmp(suffix, "M") == 0 ||
        strcmp(suffix, "G") == 0 || strcmp(suffix, "T") == 0) {
        return true;
    }

    if (strcmp(suffix, "KB") == 0 || strcmp(suffix, "MB") == 0 ||
        strcmp(suffix, "GB") == 0 || strcmp(suffix, "TB") == 0 ||
        strcmp(suffix, "bytes") == 0 || strcmp(suffix, "b") == 0) {
        return true;
    }

    if (strcmp(suffix, "KiB") == 0 || strcmp(suffix, "MiB") == 0 ||
        strcmp(suffix, "GiB") == 0 || strcmp(suffix, "TiB") == 0) {
        return true;
    }

    if (strcmp(suffix, "B") == 0) {
        return true;
    }

    return false;
}

static bool is_semver(const char *token)
{
    /* Semantic version: major.minor.patch[-prerelease][+build] */
    size_t len = strlen(token);
    if (len < 3) return false;

    const char *p = token;
    if (!isdigit((unsigned char)*p)) return false;

    while (*p && isdigit((unsigned char)*p)) p++;
    if (*p != '.') return false;
    p++;

    if (!isdigit((unsigned char)*p)) return false;
    while (*p && isdigit((unsigned char)*p)) p++;
    if (*p != '.') return false;
    p++;

    if (!isdigit((unsigned char)*p)) return false;
    while (*p && isdigit((unsigned char)*p)) p++;

    if (*p == '-') {
        p++;
        if (!*p) return false;
        while (*p && *p != '+') {
            if (isalnum((unsigned char)*p) || *p == '.') {
                p++;
            } else if (*p == '-') {
                return false;
            } else {
                return false;
            }
        }
    }

    if (*p == '+') {
        p++;
        if (!*p) return false;
        while (*p) {
            if (isalnum((unsigned char)*p) || *p == '.') {
                p++;
            } else {
                return false;
            }
        }
    }

    return *p == '\0';
}

static bool is_timestamp(const char *token)
{
    int y, m, d, h, min, s;

    /* Combined datetime: YYYY-MM-DDThh:mm:ss[Z|+HH:MM|+HHMM|-HH:MM] */
    size_t len = strlen(token);
    if (len >= 19 && token[4] == '-' && token[7] == '-' &&
        (token[10] == 'T' || token[10] == ' ' || token[10] == 't') &&
        token[13] == ':' && token[16] == ':') {
        if (sscanf(token, "%d-%d-%dT%d:%d:%d", &y, &m, &d, &h, &min, &s) == 6 ||
            sscanf(token, "%d-%d-%d %d:%d:%d", &y, &m, &d, &h, &min, &s) == 6) {
            if (y > 0 && m >= 1 && m <= 12 && d >= 1 && d <= 31 &&
                h >= 0 && h <= 23 && min >= 0 && min <= 59 && s >= 0 && s <= 59)
                return true;
        }
    }

    /* Simple date: YYYY-MM-DD (must have 4-digit year to avoid hostname overlap) */
    if (len == 10 && token[4] == '-' && token[7] == '-') {
        if (sscanf(token, "%d-%d-%d", &y, &m, &d) == 3 &&
            y > 0 && m >= 1 && m <= 12 && d >= 1 && d <= 31)
            return true;
    }

    /* Simple time: HH:MM:SS */
    if (len == 8 && token[2] == ':' && token[5] == ':') {
        if (sscanf(token, "%d:%d:%d", &h, &min, &s) == 3 &&
            h >= 0 && h <= 23 && min >= 0 && min <= 59 && s >= 0 && s <= 59)
            return true;
    }

    return false;
}

static bool is_hash_algo(const char *token)
{
    static const char *algos[] = {
        "md5", "sha1", "sha224", "sha256", "sha384", "sha512",
        "blake2b", "blake2s", "ripemd160", "whirlpool"
    };
    for (size_t i = 0; i < sizeof(algos)/sizeof(algos[0]); i++) {
        if (strcmp(token, algos[i]) == 0) return true;
    }
    return false;
}

static bool is_env_var(const char *token)
{
    if (token[0] != '$') return false;
    if (token[1] == '{') {
        size_t len = strlen(token);
        if (len < 4 || token[len-1] != '}') return false;
        /* Variable name must start with letter or underscore */
        if (!isalpha((unsigned char)token[2]) && token[2] != '_') return false;
        for (size_t i = 3; i < len-1; i++) {
            if (!isalnum((unsigned char)token[i]) && token[i] != '_') return false;
        }
        return true;
    }
    if (token[1] == '\0') return false;
    /* Variable name must start with letter or underscore */
    if (!isalpha((unsigned char)token[1]) && token[1] != '_') return false;
    for (const char *p = token + 2; *p; p++) {
        if (!isalnum((unsigned char)*p) && *p != '_') return false;
    }
    return true;
}

static bool is_hyphenated(const char *token)
{
    /* Match hyphenated identifiers: a-b where both a and b are 1+ chars
     * of [A-Za-z0-9_]. First char must be alpha or underscore.
     * Examples: user-42, alice-smith, not-a-date. */
    if (!token[0]) return false;
    if (!isalpha((unsigned char)token[0]) && token[0] != '_') return false;

    bool has_hyphen = false;
    for (const char *p = token + 1; *p; p++) {
        if (*p == '-') {
            has_hyphen = true;
        } else if (!isalnum((unsigned char)*p) && *p != '_') {
            return false;
        }
    }
    return has_hyphen;
}

/* ============================================================
 * PUBLIC: CLASSIFY
 * ============================================================ */

st_token_type_t st_classify_token(const char *token)
{
    if (!token || !token[0]) return ST_TYPE_LITERAL;

    /* Absolute path */
    if (is_absolute_path(token)) return ST_TYPE_ABS_PATH;

    /* URL */
    if (is_url(token)) return ST_TYPE_URL;

    /* IPv4 */
    if (is_ipv4(token)) return ST_TYPE_IPV4;

    /* Hex number (0x...) - check before hex hash which requires alpha */
    if (is_hex_number(token)) return ST_TYPE_NUMBER;

    /* UUID */
    if (is_uuid(token)) return ST_TYPE_UUID;

    /* Email */
    if (is_email(token)) return ST_TYPE_EMAIL;

    /* Hostname */
    if (is_hostname(token)) return ST_TYPE_HOSTNAME;

    /* Size */
    if (is_size(token)) return ST_TYPE_SIZE;

    /* Semantic version */
    if (is_semver(token)) return ST_TYPE_SEMVER;

    /* Decimal number - check before hex hash which requires alpha */
    if (is_decimal_number(token)) return ST_TYPE_NUMBER;

    /* Port (numbers 1-65535, after decimal to avoid classification overlap) */
    if (is_port(token)) return ST_TYPE_PORT;

    /* Timestamp (ISO 8601 date/time before option check to avoid misclassifying dates) */
    if (is_timestamp(token)) return ST_TYPE_TIMESTAMP;

    /* Hash algorithm names (sha256, md5, etc.) */
    if (is_hash_algo(token)) return ST_TYPE_HASH_ALGO;

    /* Environment variable ($VAR, ${VAR}) */
    if (is_env_var(token)) return ST_TYPE_ENV_VAR;

    /* Username (requires _ or - to distinguish from bare command names) */
    if (is_hyphenated(token)) return ST_TYPE_HYPHENATED;

    /* Option token (-v, --help, -o file) */
    if (is_option_token(token)) return ST_TYPE_OPT;

    /* Hex hash (8+ hex chars with at least one letter, no 0x prefix) */
    if (is_hex_hash(token)) return ST_TYPE_HEXHASH;

    /* Relative path (has / or ..) */
    if (is_relative_path(token)) return ST_TYPE_REL_PATH;

    /* Filename (has ., no /) */
    if (is_filename(token)) return ST_TYPE_FILENAME;

    /* Words are LITERAL by default - they could be command names,
     * subcommands, or fixed arguments. Only classify as #w when
     * the context indicates a variable position (after long flags,
     * redirections, etc.) - handled by the caller. */

    /* Quoted string with whitespace */
    if (has_whitespace(token)) return ST_TYPE_QUOTED_SPACE;

    /* Default: literal */
    return ST_TYPE_LITERAL;
}

/* ============================================================
 * TOKENISATION
 * ============================================================ */

static char **tokenize_command(const char *raw_cmd, size_t *out_count)
{
    size_t len = strlen(raw_cmd);
    size_t max_tokens = len / 2 + 2;
    char **tokens = calloc(max_tokens, sizeof(char *));
    if (!tokens) return NULL;

    size_t count = 0;
    const char *p = raw_cmd;

    while (*p) {
        while (*p && isspace((unsigned char)*p)) p++;
        if (!*p) break;

        /* Check for pipe */
        if (*p == '|') {
            tokens[count] = strdup("|");
            if (!tokens[count]) goto fail;
            count++;
            p++;
            continue;
        }

        /* Check for redirection operators */
        bool found_redir = false;
        const char *redir_start = p;
        if (*p == '&' && (p[1] == '>' || (p[1] == '>' && p[2] == '>'))) {
            size_t rlen = (p[2] == '>') ? 3 : 2;
            tokens[count] = strndup(redir_start, rlen);
            if (!tokens[count]) goto fail;
            count++;
            p += rlen;
            found_redir = true;
        } else if (*p == '2' && (p[1] == '>' || (p[1] == '>' && p[2] == '>'))) {
            size_t rlen = (p[2] == '>') ? 3 : 2;
            tokens[count] = strndup(redir_start, rlen);
            if (!tokens[count]) goto fail;
            count++;
            p += rlen;
            found_redir = true;
        } else if (*p == '>' && p[1] == '>') {
            tokens[count] = strdup(">>");
            if (!tokens[count]) goto fail;
            count++;
            p += 2;
            found_redir = true;
        } else if (*p == '>' || *p == '<') {
            char buf[3] = { *p, '\0', '\0' };
            tokens[count] = strdup(buf);
            if (!tokens[count]) goto fail;
            count++;
            p++;
            found_redir = true;
        }
        if (found_redir) continue;

        /* Quoted string */
        char quote = 0;
        if (*p == '"' || *p == '\'') {
            quote = *p;
            p++;
            const char *start = p;
            while (*p && *p != quote) {
                if (*p == '\\' && p[1]) p++;
                p++;
            }
            tokens[count] = strndup(start, (size_t)(p - start));
            if (!tokens[count]) goto fail;
            count++;
            if (*p == quote) p++;
            continue;
        }

        /* Regular token */
        const char *start = p;
        while (*p && !isspace((unsigned char)*p) &&
               *p != '|' && *p != '>' && *p != '<' && *p != '&') {
            p++;
        }
        /* If no characters were consumed (e.g. standalone '&' or other
         * special char not handled above), treat as single-char token */
        if (p == start && *p) {
            p++;
        }
        tokens[count] = strndup(start, (size_t)(p - start));
        if (!tokens[count]) goto fail;
        count++;
    }

    *out_count = count;
    return tokens;

fail:
    for (size_t i = 0; i < count; i++) free(tokens[i]);
    free(tokens);
    return NULL;
}

/* ============================================================
 * PUBLIC API: TYPED NORMALISATION
 * ============================================================ */

st_error_t st_normalize_typed(const char *raw_cmd, st_token_array_t *out)
{
    if (!raw_cmd || !out) return ST_ERR_INVALID;

    size_t raw_count = 0;
    char **raw_tokens = tokenize_command(raw_cmd, &raw_count);
    if (!raw_tokens) return ST_ERR_MEMORY;

    /* Empty command: return empty token array */
    if (raw_count == 0) {
        free(raw_tokens);
        out->tokens = NULL;
        out->count = 0;
        return ST_OK;
    }

    /* Worst case: every token splits into 2 (e.g., --flag=value → 2 tokens) */
    out->tokens = calloc(raw_count * 2, sizeof(st_token_t));
    if (!out->tokens) {
        for (size_t i = 0; i < raw_count; i++) free(raw_tokens[i]);
        free(raw_tokens);
        return ST_ERR_MEMORY;
    }
    out->count = 0;

    const char *prev = NULL;
    for (size_t i = 0; i < raw_count; i++) {
        const char *tok = raw_tokens[i];

        /* Handle --flag=value: split into --flag and value */
        if (tok[0] == '-' && tok[1] == '-') {
            const char *eq = strchr(tok + 2, '=');
            if (eq) {
                size_t flag_len = (size_t)(eq - tok);
                out->tokens[out->count].text = strndup(tok, flag_len);
                if (!out->tokens[out->count].text) goto fail;
                out->tokens[out->count].type = ST_TYPE_LITERAL;
                out->count++;

                out->tokens[out->count].text = strdup(eq + 1);
                if (!out->tokens[out->count].text) goto fail;
                out->tokens[out->count].type = st_classify_token(eq + 1);
                out->count++;

                prev = tok;
                continue;
            }
        }

        /* Handle env assignment: VAR=value → VAR= + value */
        bool is_env = false;
        const char *eq = strchr(tok, '=');
        if (eq && eq != tok) {
            is_env = true;
            for (const char *c = tok; c < eq; c++) {
                if (!isalnum((unsigned char)*c) && *c != '_') { is_env = false; break; }
            }
        }
        if (is_env) {
            size_t var_len = (size_t)(eq - tok);
            out->tokens[out->count].text = malloc(var_len + 2);
            if (!out->tokens[out->count].text) goto fail;
            memcpy(out->tokens[out->count].text, tok, var_len);
            out->tokens[out->count].text[var_len] = '=';
            out->tokens[out->count].text[var_len + 1] = '\0';
            out->tokens[out->count].type = ST_TYPE_LITERAL;
            out->count++;

            out->tokens[out->count].text = strdup(eq + 1);
            if (!out->tokens[out->count].text) goto fail;
            out->tokens[out->count].type = st_classify_token(eq + 1);
            out->count++;

            prev = tok;
            continue;
        }

        /* Pipes and redirections are structural literals */
        if (strcmp(tok, "|") == 0 ||
            strcmp(tok, ">") == 0 || strcmp(tok, ">>") == 0 ||
            strcmp(tok, "<") == 0 || strcmp(tok, "2>") == 0 ||
            strcmp(tok, "2>>") == 0 || strcmp(tok, "&>") == 0 ||
            strcmp(tok, "&>>") == 0 || strcmp(tok, ">&") == 0) {
            out->tokens[out->count].text = strdup(tok);
            if (!out->tokens[out->count].text) goto fail;
            out->tokens[out->count].type = ST_TYPE_LITERAL;
            out->count++;
            prev = tok;
            continue;
        }

        /* Long flag (--something) followed by a separate token → next token is a value.
         * Short flags (-X, -la) are kept as literals; we don't generalise their values. */
        if (prev && prev[0] == '-' && prev[1] == '-' && strchr(prev + 2, '=') == NULL) {
            /* This token is a value after a long flag */
            out->tokens[out->count].text = strdup(tok);
            if (!out->tokens[out->count].text) goto fail;
            out->tokens[out->count].type = st_classify_token(tok);
            out->count++;
            prev = tok;
            continue;
        }

        /* Token after a redirection operator → value */
        if (prev && (strcmp(prev, ">") == 0 || strcmp(prev, ">>") == 0 ||
                     strcmp(prev, "<") == 0 || strcmp(prev, "2>") == 0 ||
                     strcmp(prev, "2>>") == 0 || strcmp(prev, "&>") == 0 ||
                     strcmp(prev, "&>>") == 0 || strcmp(prev, ">&") == 0)) {
            out->tokens[out->count].text = strdup(tok);
            if (!out->tokens[out->count].text) goto fail;
            out->tokens[out->count].type = st_classify_token(tok);
            out->count++;
            prev = tok;
            continue;
        }

        /* Default: classify the token */
        out->tokens[out->count].text = strdup(tok);
        if (!out->tokens[out->count].text) goto fail;
        out->tokens[out->count].type = st_classify_token(tok);
        out->count++;
        prev = tok;
    }

    for (size_t i = 0; i < raw_count; i++) free(raw_tokens[i]);
    free(raw_tokens);
    return ST_OK;

fail:
    for (size_t i = 0; i < out->count; i++) free(out->tokens[i].text);
    free(out->tokens);
    out->tokens = NULL;
    out->count = 0;
    for (size_t i = 0; i < raw_count; i++) free(raw_tokens[i]);
    free(raw_tokens);
    return ST_ERR_MEMORY;
}

void st_free_token_array(st_token_array_t *arr)
{
    if (!arr) return;
    for (size_t i = 0; i < arr->count; i++) free(arr->tokens[i].text);
    free(arr->tokens);
    arr->tokens = NULL;
    arr->count = 0;
}

/* ============================================================
 * PUBLIC API: LEGACY STRING NORMALISATION
 * ============================================================ */

st_error_t st_normalize(const char *raw_cmd, char ***out_tokens, size_t *out_token_count)
{
    if (!raw_cmd || !out_tokens || !out_token_count) return ST_ERR_INVALID;

    st_token_array_t typed;
    typed.tokens = NULL;
    typed.count = 0;
    st_error_t err = st_normalize_typed(raw_cmd, &typed);
    if (err != ST_OK) return err;

    char **tokens = calloc(typed.count, sizeof(char *));
    if (!tokens) {
        st_free_token_array(&typed);
        return ST_ERR_MEMORY;
    }

    for (size_t i = 0; i < typed.count; i++) {
        if (typed.tokens[i].type == ST_TYPE_LITERAL) {
            tokens[i] = strdup(typed.tokens[i].text);
        } else {
            tokens[i] = strdup(st_type_symbol[typed.tokens[i].type]);
        }
        if (!tokens[i]) {
            for (size_t j = 0; j < i; j++) free(tokens[j]);
            free(tokens);
            st_free_token_array(&typed);
            return ST_ERR_MEMORY;
        }
    }

    *out_tokens = tokens;
    *out_token_count = typed.count;
    st_free_token_array(&typed);
    return ST_OK;
}

void st_free_tokens(char **tokens, size_t count)
{
    if (!tokens) return;
    for (size_t i = 0; i < count; i++) free(tokens[i]);
    free(tokens);
}
